version: "3.8"

services:
  db:
    image: docker.arvancloud.ir/postgres:16.0
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: anime_wall
      POSTGRES_USER: anime_manager
      POSTGRES_PASSWORD: complex-password
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/

  app:
    build:
      context: .
    command: ["/bin/bash", "/app/wait-for-it.sh" , "db:5432", "--", "/app/run.sh"]
    container_name: app
    restart: always
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: "2=9xkub-2t$*g4!&8hgjob53onzut)k+nye47-^l$r(@rs=90n"
      APP_HOST: amazed-shepherd-engaging.ngrok-free.app
      DIVAR_IDENTIFICATION_KEY: complex-identification-key
      KENAR_APP_SLUG: luck-proud-sparrow
      KENAR_API_KEY: eyJhbGciOiJSUzI1NiIsImtpZCI6InByaXZhdGVfa2V5XzIiLCJ0eXAiOiJKV1QifQ.eyJhcHBfc2x1ZyI6Imx1Y2stcHJvdWQtc3BhcnJvdyIsImF1ZCI6InNlcnZpY2Vwcm92aWRlcnMiLCJleHAiOjE3MzMwNjY2MjksImp0aSI6IjUzMjJlNWUzLTgwZDItMTFlZi04ZTg3LWZhYWIwNjE3MDlmYyIsImlhdCI6MTcyNzg4MjYyOSwiaXNzIjoiZGl2YXIiLCJzdWIiOiJhcGlrZXkifQ.IDgsOUIMKBPYxdvJqBlhHQxfi-czGkCZpSgP7tlvDko7mQwBj5k4mKmklsr80jRHhEGc7ULPJHhNE43bOdAeGcFbTjYsKj1JZE76_2ndcrfUKwv9-tkalcIaCMiXJi_3nDZX4jj8VLj7PxGl8kPeFSPPtrvVoxMwNkDRqaOSUaIvhMXYYARWlsom9W7UWapelIxLatbh8gVhiV1eP6B7WcAWy1VkS-X9qF9H84Rcr80yDcAdo2C_wIbd6qaCRNucucHwtQ8uEWnnXWmZzLp0T8F7lnF5Jxgr0IEO938_addtpisVdOoSpAnM5K4apiJA_Pz0i5yyAk2KRE7ZdQjmgQ
      KENAR_OAUTH_SECRET: bdd733348c4f7cd0f9aa14c369c714275c1d7be4efcc108a76b4ce7652230d9d374c9992bb565783e0cc42382c5bd9ae4ec250137be1c26441332d9bc1d54535
      DATABASE_NAME: anime_wall
      DATABASE_USER: anime_manager
      DATABASE_PASSWORD: complex-password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./.:/app/

  ngrok:
    image: docker.arvancloud.ir/ngrok/ngrok
    container_name: ngrok
    command: ["http", "--domain=amazed-shepherd-engaging.ngrok-free.app", "8000"]
    network_mode: "host"
    environment:
       NGROK_AUTHTOKEN: 2NaaCQYjniNDPT1UxniMYkVMMWO_7yR6ozZiQpZnAendVoJxq
